Feature/pla 9753 expose cross team resource listing endpoints
CitrineInformatics/citrine-python pull request #769
Opened 2022-07-07 18:38 UTC by crleblanc

# Citrine Python PR

## Description 
As per PLA-9753 this PR gives users a way of listing published resources in a team, e.g. `team.dataset_ids.list_readable()`.  This returns a list of IDs.  This is not a great user experience, but our auth layer only records UIDs, so we would need additional APIs to hydrate these resources efficiently (e.g. getting a batch of resources).

There will be a PR for devkit to include an e2e for this functionality, once this PR is merged.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Maintenance (non-breaking change to assist developers)

### Adherence to team decisions
- [X] I have added tests for 100% coverage
- [X] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [X] I have bumped the version in setup.py

2022-07-07 19:37 UTC, kroenlein requested changes
The build a collection then enumerate a set of methods doesn't quite align with my design aesthetic, but it's internally consistent and gets the job done.  I'll approve once you address the specific changes below.

( I'd probably have created one `resource_ids` method with the access and type arguments that take enumerations. )

2022-07-07 19:37 UTC, kroenlein commented on src/citrine/resources/team.py
> +        return self._list_ids(action="READ")
This should be the module constant.
```suggestion
        return self._list_ids(action=READ)
```

2022-07-07 19:37 UTC, kroenlein commented on src/citrine/resources/team.py
> +        return self._list_ids(action="WRITE")
This should be the module constant.
```suggestion
        return self._list_ids(action=WRITE)
```

2022-07-07 19:37 UTC, kroenlein commented on src/citrine/resources/team.py
> +        return self._list_ids(action="SHARE")
This should be the module constant.
```suggestion
        return self._list_ids(action=SHARE)
```

2022-07-07 19:37 UTC, kroenlein commented on src/citrine/resources/team.py
> +        return format_escaped_url(f'/teams/{str(self.team_id)}')
I believe the f-string automatically casts as `str` by default
```suggestion
        return format_escaped_url(f'/teams/{self.team_id}')
```

2022-07-13 15:31 UTC, kroenlein approved these changes
Makes sense as written.  

Would make more sense to me grammatically if the syntax were:
```python
team.datasets.list_readable_ids()
```
but I appreciate that implementing that would be more complicated.

2022-07-13 22:54 UTC, crleblanc commented
> Makes sense as written.
> 
> Would make more sense to me grammatically if the syntax were:
> 
> ```python
> team.datasets.list_readable_ids()
> ```
> 
> but I appreciate that implementing that would be more complicated.

I agree that this would be much cleaner, but this is not the DatasetCollection instance we get elsewhere, e.g. project.datasets.  I suspect this could get confusing for users who would expect a fully hydrated resource collection but instead get IDs back.

I wonder if we'll have to revisit this in the future and make batch-get endpoints to facilitate a proper resource collection?  The user workflow would be smoother.

2022-07-14 16:25 UTC, merged